// Photo pool for the screensaver. Each entry is a data URI string.
//
// This file is regenerated by `scripts/refresh-photos.sh` from whatever
// images live in `~/Pictures/Polaroids for Mom/` on the build machine. It
// ships empty in source control so personal photos are never committed.
//
// To populate:
//   1. Drop .jpg / .jpeg / .png files into ~/Pictures/Polaroids for Mom/
//   2. Run `bash scripts/refresh-photos.sh`
//
// To see the expected shape without your own photos, copy
// `photos-data.example.js` over this file.
window.POLAROIDS_PHOTOS = [];
