#!/bin/bash
# refresh-photos.sh — Bake a folder of photos into runtime/web/js/photos-data.js
# for development. Mirrors what ship/Refresh\ Photos.command does for the
# installed .saver bundle, but writes to the source repo instead.
#
# Usage:
#   bash scripts/refresh-photos.sh                  # reads ~/Pictures/Polaroids for Mom
#   bash scripts/refresh-photos.sh /path/to/photos  # custom directory
#
# Photos are resized to max-edge 1600px @ JPEG q=85 via macOS `sips`, then
# base64-encoded into the manifest. Personal photos stay in your filesystem
# and the `.gitignore` keeps photos-data.js out of git history.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${1:-$HOME/Pictures/Polaroids for Mom}"
OUT="$REPO_ROOT/runtime/web/js/photos-data.js"

if [ ! -d "$SRC" ]; then
  echo "Creating photo folder: $SRC"
  mkdir -p "$SRC"
  echo "Drop .jpg / .jpeg / .png files in there and re-run."
  exit 0
fi

COUNT=$(find "$SRC" -maxdepth 1 -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) | wc -l | tr -d ' ')
if [ "$COUNT" -eq 0 ]; then
  echo "No photos in $SRC yet. Drop some .jpg / .png files in there and re-run."
  exit 1
fi

echo "[refresh] $COUNT photos found. Resizing and encoding into $OUT ..."

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

{
  echo "// Auto-generated by scripts/refresh-photos.sh — DO NOT COMMIT."
  echo "// This file holds personal photos as data URIs; .gitignore keeps it out of history."
  echo "window.POLAROIDS_PHOTOS = ["
  i=0
  while IFS= read -r -d '' photo; do
    sips -Z 1600 -s format jpeg -s formatOptions 85 "$photo" --out "$TMP/p_$i.jpg" >/dev/null 2>&1 || cp "$photo" "$TMP/p_$i.jpg"
    B64=$(base64 < "$TMP/p_$i.jpg" | tr -d '\n')
    if [ "$i" -gt 0 ]; then echo ","; fi
    printf '  "data:image/jpeg;base64,%s"' "$B64"
    i=$((i + 1))
  done < <(find "$SRC" -maxdepth 1 -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) -print0 | sort -z)
  echo ""
  echo "];"
} > "$OUT"

echo "Done. $OUT now holds $COUNT photos."
